/**
 * CANONICAL_ORIGIN
 */
export const CANONICAL_ORIGIN = process.env.NEXT_PUBLIC_CANONICAL_ORIGIN

/**
 * TECDDY_TWITTER_ID
 */
export const TECDDY_TWITTER_ID = process.env.NEXT_PUBLIC_TECDDY_TWITTER_ID
