/**
 * CANONICAL_ORIGIN
 */
const NEXT_PUBLIC_CANONICAL_ORIGIN = process.env.NEXT_PUBLIC_CANONICAL_ORIGIN;
if (!NEXT_PUBLIC_CANONICAL_ORIGIN) {
  throw new Error(`env.NEXT_PUBLIC_CANONICAL_ORIGIN`);
}
export const CANONICAL_ORIGIN = NEXT_PUBLIC_CANONICAL_ORIGIN;

/**
 * AUTH_API_ORIGIN
 */
const NEXT_PUBLIC_AUTH_API_ORIGIN = process.env.NEXT_PUBLIC_AUTH_API_ORIGIN;

if (!NEXT_PUBLIC_AUTH_API_ORIGIN) {
  throw new Error(`env.NEXT_PUBLIC_AUTH_API_ORIGIN`);
}

export const AUTH_API_ORIGIN = NEXT_PUBLIC_AUTH_API_ORIGIN;

/**
 * UPLOAD_API_ORIGIN
 */
const NEXT_PUBLIC_UPLOAD_API_ORIGIN = process.env.NEXT_PUBLIC_UPLOAD_API_ORIGIN;

if (!NEXT_PUBLIC_UPLOAD_API_ORIGIN) {
  throw new Error(`env.NEXT_PUBLIC_UPLOAD_API_ORIGIN`);
}

export const UPLOAD_API_ORIGIN = NEXT_PUBLIC_UPLOAD_API_ORIGIN;

/**
 * DOMAIN_API_ORIGIN
 */
const NEXT_PUBLIC_DOMAIN_API_ORIGIN = process.env.NEXT_PUBLIC_DOMAIN_API_ORIGIN;

if (!NEXT_PUBLIC_DOMAIN_API_ORIGIN) {
  throw new Error(`env.NEXT_PUBLIC_DOMAIN_API_ORIGIN`);
}

export const DOMAIN_API_ORIGIN = NEXT_PUBLIC_DOMAIN_API_ORIGIN;

/**
 * TALENT_ORIGIN
 */
const NEXT_PUBLIC_TALENT_ORIGIN = process.env.NEXT_PUBLIC_TALENT_ORIGIN;

if (!NEXT_PUBLIC_TALENT_ORIGIN) {
  throw new Error(`env.NEXT_PUBLIC_TALENT_ORIGIN`);
}

export const TALENT_ORIGIN = NEXT_PUBLIC_TALENT_ORIGIN;

/**
 * EMPLOYER_ORIGIN
 */
const NEXT_PUBLIC_EMPLOYER_ORIGIN = process.env.NEXT_PUBLIC_EMPLOYER_ORIGIN;

if (!NEXT_PUBLIC_EMPLOYER_ORIGIN) {
  throw new Error(`env.NEXT_PUBLIC_EMPLOYER_ORIGIN`);
}

export const EMPLOYER_ORIGIN = NEXT_PUBLIC_EMPLOYER_ORIGIN;

/**
 * TECDDY_TWITTER_ID
 */
export const TECDDY_TWITTER_ID = process.env.NEXT_PUBLIC_TECDDY_TWITTER_ID;
